### ISSUE TITLE
Composer install error

### ISSUE THREAD

**Issue by fusedtechresource** [bkintanar/HRis#51]
i tried to clone your repo to test the api but got error from composer install

Please see attached files. thanks
![composer](https://cloud.githubusercontent.com/assets/20183632/21640632/a4798842-d2b1-11e6-8f81-f880ea88eced.png)

**Comment by bkintanar** [comment]
Thanks for the report @fusedtechresource. I think that's a package problem, but I believe that `composer update` command was successful. only the post-update-cmd failed. I'll try to fix this but you can continue to test the api.

**Comment by bkintanar** [comment]
This is now fixed.
